import type { IndexData } from '@/types/market'

export const INDICES: IndexData[] = [
  {
    slug: 'sp500',
    name: 'S&P 500',
    shortName: 'S&P 500',
    symbol: 'FOREXCOM:SPXUSD',
    tvSymbol: 'FOREXCOM:SPXUSD',
    region: 'United States',
    currency: 'USD',
    description: 'Tracks 500 large-cap US companies across all sectors. The broadest barometer of US equity markets.',
  },
  {
    slug: 'nasdaq',
    name: 'NASDAQ 100',
    shortName: 'NASDAQ',
    symbol: 'FOREXCOM:NSXUSD',
    tvSymbol: 'FOREXCOM:NSXUSD',
    region: 'United States',
    currency: 'USD',
    description: 'Tracks 100 of the largest non-financial companies listed on the NASDAQ exchange, heavily weighted in tech.',
  },
  {
    slug: 'dow-jones',
    name: 'Dow Jones Industrial Average',
    shortName: 'Dow Jones',
    symbol: 'DJ:DJI',
    tvSymbol: 'DJ:DJI',
    region: 'United States',
    currency: 'USD',
    description: 'Price-weighted index of 30 large, publicly-owned US blue-chip companies.',
  },
  {
    slug: 'russell2000',
    name: 'Russell 2000',
    shortName: 'Russell 2000',
    symbol: 'TVC:RUT',
    tvSymbol: 'TVC:RUT',
    region: 'United States',
    currency: 'USD',
    description: 'Tracks 2,000 small-cap US companies. A key indicator of domestic economic health.',
  },
  {
    slug: 'vix',
    name: 'Volatility Index',
    shortName: 'VIX',
    symbol: 'TVC:VIX',
    tvSymbol: 'TVC:VIX',
    region: 'United States',
    currency: 'USD',
    description: "The market's expectation of 30-day volatility. Known as the 'fear gauge' of Wall Street.",
  },
  {
    slug: 'dax',
    name: 'DAX 40',
    shortName: 'DAX',
    symbol: 'XETR:DAX',
    tvSymbol: 'XETR:DAX',
    region: 'Germany',
    currency: 'EUR',
    description: 'Tracks 40 major German blue-chip companies listed on the Frankfurt Stock Exchange.',
  },
  {
    slug: 'ftse100',
    name: 'FTSE 100',
    shortName: 'FTSE 100',
    symbol: 'SPREADEX:FTSE',
    tvSymbol: 'SPREADEX:FTSE',
    region: 'United Kingdom',
    currency: 'GBP',
    description: "Tracks the 100 largest companies by market cap listed on the London Stock Exchange.",
  },
  {
    slug: 'nikkei',
    name: 'Nikkei 225',
    shortName: 'Nikkei',
    symbol: 'TVC:NI225',
    tvSymbol: 'TVC:NI225',
    region: 'Japan',
    currency: 'JPY',
    description: 'The leading stock market index for the Tokyo Stock Exchange, tracking 225 large Japanese firms.',
  },
]

export const TICKER_TAPE_SYMBOLS = [
  { proName: 'FOREXCOM:SPXUSD', title: 'S&P 500' },
  { proName: 'FOREXCOM:NSXUSD', title: 'NASDAQ 100' },
  { proName: 'DJ:DJI', title: 'Dow Jones' },
  { proName: 'TVC:RUT', title: 'Russell 2000' },
  { proName: 'TVC:VIX', title: 'VIX' },
  { proName: 'XETR:DAX', title: 'DAX 40' },
  { proName: 'SPREADEX:FTSE', title: 'FTSE 100' },
  { proName: 'TVC:NI225', title: 'Nikkei 225' },
  { proName: 'TVC:GOLD', title: 'Gold' },
  { proName: 'TVC:SILVER', title: 'Silver' },
  { proName: 'NYMEX:CL1!', title: 'Crude Oil' },
  { proName: 'CRYPTOCAP:BTC.D', title: 'BTC Dominance' },
]

export const getIndexBySlug = (slug: string): IndexData | undefined =>
  INDICES.find((i) => i.slug === slug)
