import type { SectorData } from '@/types/market'

export const SECTORS: SectorData[] = [
  {
    slug: 'technology',
    name: 'Technology',
    description: 'Software, hardware, semiconductors, and cloud computing companies driving digital transformation.',
    etfSymbol: 'AMEX:XLK',
    tvSymbol: 'AMEX:XLK',
    keywords: ['technology stocks', 'semiconductor', 'artificial intelligence', 'cloud computing', 'Apple', 'Microsoft', 'NVIDIA', 'software'],
    iconName: 'Cpu',
    color: 'blue',
    stocks: [
      { symbol: 'AAPL', name: 'Apple', tvSymbol: 'NASDAQ:AAPL' },
      { symbol: 'MSFT', name: 'Microsoft', tvSymbol: 'NASDAQ:MSFT' },
      { symbol: 'NVDA', name: 'NVIDIA', tvSymbol: 'NASDAQ:NVDA' },
      { symbol: 'GOOGL', name: 'Alphabet', tvSymbol: 'NASDAQ:GOOGL' },
    ],
  },
  {
    slug: 'healthcare',
    name: 'Healthcare',
    description: 'Pharmaceuticals, biotechnology, medical devices, and healthcare services companies.',
    etfSymbol: 'AMEX:XLV',
    tvSymbol: 'AMEX:XLV',
    keywords: ['pharma', 'biotech', 'FDA approval', 'drug', 'medical device', 'healthcare', 'clinical trial'],
    iconName: 'HeartPulse',
    color: 'green',
    stocks: [
      { symbol: 'JNJ', name: 'Johnson & Johnson', tvSymbol: 'NYSE:JNJ' },
      { symbol: 'UNH', name: 'UnitedHealth', tvSymbol: 'NYSE:UNH' },
      { symbol: 'LLY', name: 'Eli Lilly', tvSymbol: 'NYSE:LLY' },
      { symbol: 'PFE', name: 'Pfizer', tvSymbol: 'NYSE:PFE' },
    ],
  },
  {
    slug: 'financials',
    name: 'Financials',
    description: 'Banks, insurance, investment firms, and fintech companies shaping global finance.',
    etfSymbol: 'AMEX:XLF',
    tvSymbol: 'AMEX:XLF',
    keywords: ['Federal Reserve', 'interest rates', 'banking', 'JPMorgan', 'Goldman Sachs', 'inflation', 'fintech', 'insurance'],
    iconName: 'Landmark',
    color: 'yellow',
    stocks: [
      { symbol: 'JPM', name: 'JPMorgan Chase', tvSymbol: 'NYSE:JPM' },
      { symbol: 'BAC', name: 'Bank of America', tvSymbol: 'NYSE:BAC' },
      { symbol: 'GS', name: 'Goldman Sachs', tvSymbol: 'NYSE:GS' },
      { symbol: 'BRK.B', name: 'Berkshire Hathaway', tvSymbol: 'NYSE:BRK.B' },
    ],
  },
  {
    slug: 'energy',
    name: 'Energy',
    description: 'Oil, gas, renewables, and energy infrastructure companies powering the global economy.',
    etfSymbol: 'AMEX:XLE',
    tvSymbol: 'AMEX:XLE',
    keywords: ['oil prices', 'OPEC', 'natural gas', 'crude oil', 'energy', 'renewable energy', 'ExxonMobil', 'Chevron'],
    iconName: 'Zap',
    color: 'orange',
    stocks: [
      { symbol: 'XOM', name: 'ExxonMobil', tvSymbol: 'NYSE:XOM' },
      { symbol: 'CVX', name: 'Chevron', tvSymbol: 'NYSE:CVX' },
      { symbol: 'COP', name: 'ConocoPhillips', tvSymbol: 'NYSE:COP' },
      { symbol: 'SLB', name: 'SLB', tvSymbol: 'NYSE:SLB' },
    ],
  },
  {
    slug: 'consumer-discretionary',
    name: 'Consumer',
    description: 'Retail, e-commerce, automotive, and entertainment companies tied to consumer spending.',
    etfSymbol: 'AMEX:XLY',
    tvSymbol: 'AMEX:XLY',
    keywords: ['retail sales', 'consumer spending', 'Amazon', 'e-commerce', 'Tesla', 'automotive', 'luxury goods'],
    iconName: 'ShoppingBag',
    color: 'pink',
    stocks: [
      { symbol: 'AMZN', name: 'Amazon', tvSymbol: 'NASDAQ:AMZN' },
      { symbol: 'TSLA', name: 'Tesla', tvSymbol: 'NASDAQ:TSLA' },
      { symbol: 'HD', name: 'Home Depot', tvSymbol: 'NYSE:HD' },
      { symbol: 'MCD', name: "McDonald's", tvSymbol: 'NYSE:MCD' },
    ],
  },
  {
    slug: 'industrials',
    name: 'Industrials',
    description: 'Aerospace, defense, machinery, transportation, and infrastructure companies.',
    etfSymbol: 'AMEX:XLI',
    tvSymbol: 'AMEX:XLI',
    keywords: ['manufacturing', 'aerospace', 'defense', 'supply chain', 'freight', 'Boeing', 'Caterpillar', 'infrastructure'],
    iconName: 'Factory',
    color: 'slate',
    stocks: [
      { symbol: 'CAT', name: 'Caterpillar', tvSymbol: 'NYSE:CAT' },
      { symbol: 'BA', name: 'Boeing', tvSymbol: 'NYSE:BA' },
      { symbol: 'HON', name: 'Honeywell', tvSymbol: 'NASDAQ:HON' },
      { symbol: 'RTX', name: 'RTX Corp', tvSymbol: 'NYSE:RTX' },
    ],
  },
  {
    slug: 'communication',
    name: 'Communication',
    description: 'Telecom, media, social networks, and streaming services connecting the world.',
    etfSymbol: 'AMEX:XLC',
    tvSymbol: 'AMEX:XLC',
    keywords: ['telecom', 'social media', 'streaming', 'media', 'Meta', 'Netflix', 'Alphabet', 'communication'],
    iconName: 'Radio',
    color: 'violet',
    stocks: [
      { symbol: 'META', name: 'Meta Platforms', tvSymbol: 'NASDAQ:META' },
      { symbol: 'NFLX', name: 'Netflix', tvSymbol: 'NASDAQ:NFLX' },
      { symbol: 'T', name: 'AT&T', tvSymbol: 'NYSE:T' },
      { symbol: 'DIS', name: 'Disney', tvSymbol: 'NYSE:DIS' },
    ],
  },
  {
    slug: 'materials',
    name: 'Materials',
    description: 'Mining, chemicals, construction materials, and packaging companies.',
    etfSymbol: 'AMEX:XLB',
    tvSymbol: 'AMEX:XLB',
    keywords: ['mining', 'gold', 'copper', 'steel', 'chemicals', 'commodities', 'materials', 'lithium'],
    iconName: 'Gem',
    color: 'emerald',
    stocks: [
      { symbol: 'LIN', name: 'Linde', tvSymbol: 'NASDAQ:LIN' },
      { symbol: 'APD', name: 'Air Products', tvSymbol: 'NYSE:APD' },
      { symbol: 'NEM', name: 'Newmont', tvSymbol: 'NYSE:NEM' },
      { symbol: 'FCX', name: 'Freeport-McMoRan', tvSymbol: 'NYSE:FCX' },
    ],
  },
  {
    slug: 'utilities',
    name: 'Utilities',
    description: 'Electric, gas, and water utilities providing essential services and stable dividends.',
    etfSymbol: 'AMEX:XLU',
    tvSymbol: 'AMEX:XLU',
    keywords: ['utilities', 'electric grid', 'natural gas utility', 'power grid', 'water utility', 'dividend'],
    iconName: 'Power',
    color: 'cyan',
    stocks: [
      { symbol: 'NEE', name: 'NextEra Energy', tvSymbol: 'NYSE:NEE' },
      { symbol: 'DUK', name: 'Duke Energy', tvSymbol: 'NYSE:DUK' },
      { symbol: 'SO', name: 'Southern Company', tvSymbol: 'NYSE:SO' },
      { symbol: 'D', name: 'Dominion Energy', tvSymbol: 'NYSE:D' },
    ],
  },
  {
    slug: 'real-estate',
    name: 'Real Estate',
    description: 'REITs and real estate companies across commercial, residential, and industrial sectors.',
    etfSymbol: 'AMEX:XLRE',
    tvSymbol: 'AMEX:XLRE',
    keywords: ['REIT', 'real estate', 'commercial real estate', 'housing market', 'mortgage rates', 'property'],
    iconName: 'Building2',
    color: 'amber',
    stocks: [
      { symbol: 'AMT', name: 'American Tower', tvSymbol: 'NYSE:AMT' },
      { symbol: 'PLD', name: 'Prologis', tvSymbol: 'NYSE:PLD' },
      { symbol: 'EQIX', name: 'Equinix', tvSymbol: 'NASDAQ:EQIX' },
      { symbol: 'CCI', name: 'Crown Castle', tvSymbol: 'NYSE:CCI' },
    ],
  },
]

export const getSectorBySlug = (slug: string): SectorData | undefined =>
  SECTORS.find((s) => s.slug === slug)
